Add refund_requests API
ticketscloud/doc pull request #4
Opened 2019-07-26 13:19 UTC by nndii

Дока по возвратам

2019-07-29 07:11 UTC, Sanchoyzer commented on walkthrough/refund_requests.rst
> +       :query order: Id заказа
Можно тут кинуть рефку на тип objectid

2019-07-29 07:11 UTC, Sanchoyzer approved these changes

2019-07-30 08:11 UTC, EvgeniyMakhmudov requested changes

2019-07-30 08:11 UTC, EvgeniyMakhmudov commented on walkthrough/refund_requests.rst
> +               "vendor": objectid
Пропущено поле `finished_at`

2019-08-06 08:25 UTC, zzzsochi approved these changes

2019-08-21 08:07 UTC, EvgeniyMakhmudov approved these changes

2019-08-23 13:26 UTC, merged