TC-4833 (promocodes comeback)
ticketscloud/doc pull request #6
Opened 2019-08-28 19:43 UTC by Sanchoyzer

https://ticketscloud.atlassian.net/browse/TC-4833

Добавил информацию про промокоды

2019-08-28 21:04 UTC, EvgeniyMakhmudov requested changes

2019-08-28 21:04 UTC, EvgeniyMakhmudov commented on extra/orders.rst
> +    .. http:post:: /v2/resources/orders/:id
не post а patch раз :id указан

2019-08-28 21:04 UTC, EvgeniyMakhmudov commented on extra/orders.rst
> +                        "viral": false
я не знаю надо ли это здесь

2019-08-28 21:04 UTC, EvgeniyMakhmudov commented on walkthrough/order_finish.rst
> +                        "tickets_count": {},
выводы какие то не синхронизованные, выше про sets tickets_count ничего не сказано.

2019-08-29 07:24 UTC, EvgeniyMakhmudov approved these changes

2019-08-29 07:36 UTC, nndii approved these changes

2019-08-29 09:32 UTC, skudryavtsev commented on extra/orders.rst
> +|  cant_create_promocode       | Cant create promocode / Cant create {} promocode {}              |
@EvgeniyMakhmudov а это же первые 2 ошибки про создание промокодов? В работе с заказом таких нет ошибок вроде.

2019-08-29 12:26 UTC, EvgeniyMakhmudov commented on extra/orders.rst
> +|  cant_create_promocode       | Cant create promocode / Cant create {} promocode {}              |
Да ты прав

2019-08-29 13:05 UTC, skudryavtsev commented on extra/orders.rst
> +|  cant_create_promocode       | Cant create promocode / Cant create {} promocode {}              |
@Sanchoyzer надо убрать, чтобы не вводить в заблуждение.

2019-08-29 13:08 UTC, Sanchoyzer commented on extra/orders.rst
> +|  cant_create_promocode       | Cant create promocode / Cant create {} promocode {}              |
done

2019-08-30 08:47 UTC, merged