TC-4968 (add example)
ticketscloud/doc pull request #7
Opened 2019-09-23 16:16 UTC by Sanchoyzer

https://ticketscloud.atlassian.net/browse/TC-4968

>- Прописать в публичной документации, что ШК появляется только у заказа в статусе done
>- Нужна задача добавить в публичную документацию описание процесса смешанного заказа когда и с рассадкой и без в одном заказе

2019-09-25 09:48 UTC, zzzsochi commented on walkthrough/order_example.rst
> +   Пример будет смешанного заказа из двух билетов: один билет с рассадкой, другой -- без
Что-то с русским языком тут, чую я.

2019-09-25 09:49 UTC, Sanchoyzer commented on walkthrough/order_example.rst
> +   Пример будет смешанного заказа из двух билетов: один билет с рассадкой, другой -- без
У меня в этом году 4 по Тотальному диктанту была!

2019-09-25 09:51 UTC, zzzsochi requested changes
Я не вижу примера, когда билет с местом и билет без места в одном заказе.

2019-09-25 09:53 UTC, Sanchoyzer commented
@zzzsochi , вот же
```
                "tickets": [
                    {
                        "barcode": null,
                        "discount": "0.00",
                        "extra": "666.60",
                        "full": "7332.60",
                        "id": "5d71350576a6bda00a86ad2f",
                        "nominal": "6666.00",
                        "number": 137456,
                        "price": "6666.00",
                        "serial": "PTY",
                        "set": "5d713505255895db3c30b0c5",
                        "status": "reserved"
                    },
                    {
                        "barcode": null,
                        "discount": "0.00",
                        "extra": "0.00",
                        "full": "0.00",
                        "id": "5d7134962110d30a34e95b97",
                        "nominal": "0.00",
                        "number": 135471,
                        "price": "0.00",
                        "seat": {
                            "number": "3",
                            "row": "10",
                            "sector": "5a8dd58e6e55b2064c67c142"
                        },
                        "serial": "EOY",
                        "set": "5d80caa838d7c9920bec1b47",
                        "status": "reserved"
                    }
```

2019-09-25 10:57 UTC, zzzsochi requested changes
Саш, ты не понял проблематики. Какую проблему мы решаем этим примером?

2019-09-25 11:08 UTC, Sanchoyzer commented
@zzzsochi Наверное, у тех, кто пользуется докой, возник такой вопрос, вот мы и делаем пример. А возник он из-за того, что у них такая схема

2019-09-26 11:14 UTC, zzzsochi commented on walkthrough/order_example.rst
> +            ]
А вот перевод в `done` лучше вынести отдельно. Этих билетов, например, может уже и не быть.

2019-09-26 11:17 UTC, zzzsochi requested changes
1. Нужно отделить перевод в `done`, так как возможна гонка данных, билеты не будут добавлены и клиент получит нечто неожиданное. С созданием таких проблем нет.
2. Обратный вариант тоже стоит расписать, где объяснить логику формирования `random` из списка билетов.

2019-09-26 13:39 UTC, zzzsochi approved these changes
Очень тяжело это читать. Но я лучше не умею.

2019-09-27 09:28 UTC, merged