TC-5132 (Дополнить публичную документацию)
ticketscloud/doc pull request #8
Opened 2019-10-22 18:13 UTC by Sanchoyzer

https://ticketscloud.atlassian.net/browse/TC-5132

>1. http://joxi.ru/ZrJXLEwIw6j762 — убрать бету из документации
>2. добавить описание age_rating в simple/events
>3. добавить описание deal в simple/events
>4. добавить описание partner в simple/events
>5. добавить описание tags в simple/events
>6. добавить описание tickets_amount в simple/events
>7. добавить описание tickets_amount_vacant в simple/events

2019-10-23 11:26 UTC, SoloIana requested changes

2019-10-23 11:26 UTC, IvSaladuha commented on walkthrough/events.rst
> +    - ``tickets_amount_vacant`` **int** - количество доступных для продажи билтов
Опечатка в слове "билетов".

2019-10-23 12:04 UTC, SoloIana approved these changes

2019-10-24 07:59 UTC, skudryavtsev commented on walkthrough/events.rst
> +       - ``extra`` **str** - доля сервисного сбора
Лучше назвать просто сервисным сбором распространителя.

2019-10-24 08:19 UTC, Sanchoyzer commented on walkthrough/events.rst
> +       - ``extra`` **str** - доля сервисного сбора
done

2019-10-25 08:12 UTC, EvgeniyMakhmudov commented on walkthrough/events.rst
> +    - ``tickets_amount`` **int** - количество билетов всего
Я бы заменил формулировку "Общее количество билетов", как то более по русски звучит

2019-10-25 08:23 UTC, EvgeniyMakhmudov approved these changes

2019-10-25 08:26 UTC, merged